### ISSUE TITLE
DUP - toggling off special notice closure clears text before hitting submit

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-admin#357] opened 2024-05-28 02:52 UTC
**Describe the bug**
If you toggle off the special closure notice, the text clears before clicking submit. So if you accidently toggle off the special closure notice, you lose all text in the box. Text should be retained until changes are submitted - should function same as day-of-week closure feature. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LindsayMacfarlane** [comment] 2024-10-31 21:42
Tested on October 31, 2024. I can't reproduce this error. @MarshallHenson - can you confirm if this is still a bug?

**Comment by MarshallHenson** [comment] 2024-10-31 21:46
I also noticed that this was fixed earlier in the summer.. assumed the ticket got completed. May be worth asking the devs to confirm what was done.

**Comment by LindsayMacfarlane** [comment] 2024-11-21 20:11
November 21, 2024 - DUP prioritization session. This ticket/issue was identified as medium priority, but possibly completed.

https://app.mural.co/t/bcparks2575/m/bcparks2575/1729124366479/8adea59d9e76fb3eb1e33395f1c1857a8c07fb7b 

cc @Christopher-walsh22 > can you please confirm that this is no longer an issue?

**Comment by LindsayMacfarlane** [comment] 2024-12-05 01:13
@Christopher-walsh22 - it looks like this bug is no longer an issue. Can you confirm please.

**Comment by LindsayMacfarlane** [comment] 2024-12-07 00:46
@manuji passing this along to you to help confirm if this ticket has been resolved. I believe so, but would appreciate additional eyes :)

**Comment by manuji** [comment] 2024-12-11 23:52
Tested on TEST: Passed
* Verified that this issue has been fixed. 
* Moving to Done. 

FYI @LindsayMacfarlane

**Closed by manuji** 2024-12-11 23:52 UTC
Labels: bug, DUP
